package com.gamewolf.base.model;

public class VgMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_menu.id
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_menu.menu_name
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_menu.menu_cname
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    private String menuCname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_menu.menu_icon
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    private String menuIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_menu.menu_path
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    private String menuPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_menu.menu_icon_url
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    private String menuIconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_menu.parent_id
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_menu.menu_type
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    private Integer menuType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_menu.id
     *
     * @return the value of vg_menu.id
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_menu.id
     *
     * @param id the value for vg_menu.id
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_menu.menu_name
     *
     * @return the value of vg_menu.menu_name
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_menu.menu_name
     *
     * @param menuName the value for vg_menu.menu_name
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_menu.menu_cname
     *
     * @return the value of vg_menu.menu_cname
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public String getMenuCname() {
        return menuCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_menu.menu_cname
     *
     * @param menuCname the value for vg_menu.menu_cname
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public void setMenuCname(String menuCname) {
        this.menuCname = menuCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_menu.menu_icon
     *
     * @return the value of vg_menu.menu_icon
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_menu.menu_icon
     *
     * @param menuIcon the value for vg_menu.menu_icon
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_menu.menu_path
     *
     * @return the value of vg_menu.menu_path
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_menu.menu_path
     *
     * @param menuPath the value for vg_menu.menu_path
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_menu.menu_icon_url
     *
     * @return the value of vg_menu.menu_icon_url
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public String getMenuIconUrl() {
        return menuIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_menu.menu_icon_url
     *
     * @param menuIconUrl the value for vg_menu.menu_icon_url
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public void setMenuIconUrl(String menuIconUrl) {
        this.menuIconUrl = menuIconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_menu.parent_id
     *
     * @return the value of vg_menu.parent_id
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_menu.parent_id
     *
     * @param parentId the value for vg_menu.parent_id
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_menu.menu_type
     *
     * @return the value of vg_menu.menu_type
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_menu.menu_type
     *
     * @param menuType the value for vg_menu.menu_type
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }
}