package com.gamewolf.gameinfo.mapper;

import com.gamewolf.gameinfo.model.VgInfo;
import com.gamewolf.gameinfo.model.VgInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VgInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    long countByExample(VgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    int deleteByExample(VgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    int insert(VgInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    int insertSelective(VgInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    List<VgInfo> selectByExample(VgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    VgInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    int updateByExampleSelective(@Param("row") VgInfo row, @Param("example") VgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    int updateByExample(@Param("row") VgInfo row, @Param("example") VgInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    int updateByPrimaryKeySelective(VgInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_info
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    int updateByPrimaryKey(VgInfo row);
    
    List<VgInfo> listInfo();
}