package com.gamewolf.review.model;

public class VgReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_review.id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_review.game_id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    private Long gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_review.overall_rate
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    private Integer overallRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_review.user_id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_review.is_anonimous
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    private Boolean isAnonimous;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_review.id
     *
     * @return the value of vg_review.id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_review.id
     *
     * @param id the value for vg_review.id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_review.game_id
     *
     * @return the value of vg_review.game_id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_review.game_id
     *
     * @param gameId the value for vg_review.game_id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_review.overall_rate
     *
     * @return the value of vg_review.overall_rate
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public Integer getOverallRate() {
        return overallRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_review.overall_rate
     *
     * @param overallRate the value for vg_review.overall_rate
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public void setOverallRate(Integer overallRate) {
        this.overallRate = overallRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_review.user_id
     *
     * @return the value of vg_review.user_id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_review.user_id
     *
     * @param userId the value for vg_review.user_id
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_review.is_anonimous
     *
     * @return the value of vg_review.is_anonimous
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public Boolean getIsAnonimous() {
        return isAnonimous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_review.is_anonimous
     *
     * @param isAnonimous the value for vg_review.is_anonimous
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public void setIsAnonimous(Boolean isAnonimous) {
        this.isAnonimous = isAnonimous;
    }
}