package com.gamewolf.review.model;

public class VgReviewWithBLOBs extends VgReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_review.review_cnt
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    private String reviewCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_review.review_cnt_html
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    private String reviewCntHtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_review.review_cnt
     *
     * @return the value of vg_review.review_cnt
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public String getReviewCnt() {
        return reviewCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_review.review_cnt
     *
     * @param reviewCnt the value for vg_review.review_cnt
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public void setReviewCnt(String reviewCnt) {
        this.reviewCnt = reviewCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_review.review_cnt_html
     *
     * @return the value of vg_review.review_cnt_html
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public String getReviewCntHtml() {
        return reviewCntHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_review.review_cnt_html
     *
     * @param reviewCntHtml the value for vg_review.review_cnt_html
     *
     * @mbg.generated Mon Jul 17 21:52:19 CST 2023
     */
    public void setReviewCntHtml(String reviewCntHtml) {
        this.reviewCntHtml = reviewCntHtml;
    }
}