package com.gamewolf.base.mapper;

import com.gamewolf.base.model.VgMenu;
import com.gamewolf.base.model.VgMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VgMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    long countByExample(VgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    int deleteByExample(VgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    int insert(VgMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    int insertSelective(VgMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    List<VgMenu> selectByExample(VgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    VgMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") VgMenu row, @Param("example") VgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    int updateByExample(@Param("row") VgMenu row, @Param("example") VgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(VgMenu row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vg_menu
     *
     * @mbg.generated Mon Sep 04 10:00:28 GMT+08:00 2023
     */
    int updateByPrimaryKey(VgMenu row);
}