package com.gamewolf.gameinfo.model;

import java.util.Date;

public class VgInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.gametitle_en
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private String gametitleEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.gametitle_zh
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private String gametitleZh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.dev_com_id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private Integer devComId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.dev_com_name
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private String devComName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.pub_com_id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private Integer pubComId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.pub_com_name
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private String pubComName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.release_date
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.platform
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.genreids
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private String genreids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vg_info.themes
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    private String themes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.id
     *
     * @return the value of vg_info.id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.id
     *
     * @param id the value for vg_info.id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.gametitle_en
     *
     * @return the value of vg_info.gametitle_en
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public String getGametitleEn() {
        return gametitleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.gametitle_en
     *
     * @param gametitleEn the value for vg_info.gametitle_en
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setGametitleEn(String gametitleEn) {
        this.gametitleEn = gametitleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.gametitle_zh
     *
     * @return the value of vg_info.gametitle_zh
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public String getGametitleZh() {
        return gametitleZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.gametitle_zh
     *
     * @param gametitleZh the value for vg_info.gametitle_zh
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setGametitleZh(String gametitleZh) {
        this.gametitleZh = gametitleZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.dev_com_id
     *
     * @return the value of vg_info.dev_com_id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public Integer getDevComId() {
        return devComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.dev_com_id
     *
     * @param devComId the value for vg_info.dev_com_id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setDevComId(Integer devComId) {
        this.devComId = devComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.dev_com_name
     *
     * @return the value of vg_info.dev_com_name
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public String getDevComName() {
        return devComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.dev_com_name
     *
     * @param devComName the value for vg_info.dev_com_name
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setDevComName(String devComName) {
        this.devComName = devComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.pub_com_id
     *
     * @return the value of vg_info.pub_com_id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public Integer getPubComId() {
        return pubComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.pub_com_id
     *
     * @param pubComId the value for vg_info.pub_com_id
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setPubComId(Integer pubComId) {
        this.pubComId = pubComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.pub_com_name
     *
     * @return the value of vg_info.pub_com_name
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public String getPubComName() {
        return pubComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.pub_com_name
     *
     * @param pubComName the value for vg_info.pub_com_name
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setPubComName(String pubComName) {
        this.pubComName = pubComName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.release_date
     *
     * @return the value of vg_info.release_date
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.release_date
     *
     * @param releaseDate the value for vg_info.release_date
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.platform
     *
     * @return the value of vg_info.platform
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.platform
     *
     * @param platform the value for vg_info.platform
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.genreids
     *
     * @return the value of vg_info.genreids
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public String getGenreids() {
        return genreids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.genreids
     *
     * @param genreids the value for vg_info.genreids
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setGenreids(String genreids) {
        this.genreids = genreids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vg_info.themes
     *
     * @return the value of vg_info.themes
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public String getThemes() {
        return themes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vg_info.themes
     *
     * @param themes the value for vg_info.themes
     *
     * @mbg.generated Sat Jul 15 11:37:11 CST 2023
     */
    public void setThemes(String themes) {
        this.themes = themes;
    }
}